# Netdata - Cluster monitoring
# Uses env vars to reference secret created by ExternalSecret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://netdata.github.io/helmchart
    chart: netdata
    targetRevision: 3.*
    helm:
      valuesObject:
        image:
          tag: stable
        parent:
          claiming:
            enabled: true
            token: ""
            rooms: ""
          env:
            - name: NETDATA_CLAIM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: netdata-claiming
                  key: token
            - name: NETDATA_CLAIM_ROOMS
              valueFrom:
                secretKeyRef:
                  name: netdata-claiming
                  key: rooms
            - name: NETDATA_CLAIM_URL
              value: "https://app.netdata.cloud"
        child:
          claiming:
            enabled: true
            token: ""
            rooms: ""
          env:
            - name: NETDATA_CLAIM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: netdata-claiming
                  key: token
            - name: NETDATA_CLAIM_ROOMS
              valueFrom:
                secretKeyRef:
                  name: netdata-claiming
                  key: rooms
            - name: NETDATA_CLAIM_URL
              value: "https://app.netdata.cloud"
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
