# Tailscale Operator - Helm chart installation
# Uses secret created by ExternalSecret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.*
    helm:
      valuesObject:
        oauth:
          clientId:
            existingSecret:
              name: operator-oauth
              key: client_id
          clientSecret:
            existingSecret:
              name: operator-oauth
              key: client_secret
        operatorConfig:
          hostname: talos-prod-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale-operator
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: operator-oauth
      jsonPointers:
        - /data
        - /metadata/annotations
        - /metadata/labels
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
